#!/usr/bin/env python3
"""protogen: shared/protocol/messages.md -> generated/messages_gen.{h,cpp}

messages.md defines the wire protocol in fenced ```proto blocks:

    ```proto
    message InputPath = 3
    i32 goalX
    i32 goalY
    ```

Field types: u8 u16 u32 u64 i8 i16 i32 i64 f32 bool string.
Comments start with //. IDs must be unique. Everything is little-endian.
Deterministic output (CI regenerates is NOT required; build-time codegen).
"""
import re
import sys
from pathlib import Path

FENCES = re.compile(r"```proto\s*\n(.*?)```", re.DOTALL)
HEADER = re.compile(r"^message\s+([A-Za-z][A-Za-z0-9_]*)\s*=\s*(\d+)\s*$")
FIELD = re.compile(r"^([a-z][a-z0-9]*)\s+([A-Za-z_][A-Za-z0-9_]*)$")
TYPES = {"u8", "u16", "u32", "u64", "i8", "i16", "i32", "i64", "f32", "bool", "string"}

CPP_TYPE = {
    "u8": "std::uint8_t", "u16": "std::uint16_t", "u32": "std::uint32_t",
    "u64": "std::uint64_t", "i8": "std::int8_t", "i16": "std::int16_t",
    "i32": "std::int32_t", "i64": "std::int64_t", "f32": "float",
    "bool": "bool", "string": "std::string",
}
WRITER = {"bool": "boolean", "string": "str"}
READER = {"bool": "boolean", "string": "str"}

DEFAULTS = {"string": "", "bool": "false", "f32": "0.0f"}


def parse(md_text, src):
    messages = []
    for fence_idx, block in enumerate(FENCES.findall(md_text)):
        lines = [l.split("//")[0].strip() for l in block.splitlines()]
        lines = [l for l in lines if l]
        if not lines:
            continue
        m = HEADER.match(lines[0])
        if not m:
            raise SystemExit(f"{src}: proto block #{fence_idx}: bad header: {lines[0]!r}")
        name, mid = m.group(1), int(m.group(2))
        fields = []
        for line in lines[1:]:
            f = FIELD.match(line)
            if not f:
                raise SystemExit(f"{src}: message {name}: bad field line: {line!r}")
            ftype, fname = f.group(1), f.group(2)
            if ftype not in TYPES:
                raise SystemExit(f"{src}: message {name}: unknown type {ftype!r}")
            fields.append((ftype, fname))
        messages.append((name, mid, fields))
    ids = [m[1] for m in messages]
    names = [m[0] for m in messages]
    if len(set(ids)) != len(ids):
        raise SystemExit(f"{src}: duplicate message ids")
    if len(set(names)) != len(names):
        raise SystemExit(f"{src}: duplicate message names")
    return messages


def emit_h(messages):
    out = [
        "// GENERATED by tools/protogen/protogen.py from shared/protocol/messages.md.",
        "// Do not edit by hand; bump kProtocolVersion on wire-format changes (ADR-006).",
        "#pragma once",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <string>",
        "#include <vector>",
        "",
        '#include "protocol/bytestream.h"',
        "",
        "namespace bh::proto {",
        "",
        "inline constexpr std::uint16_t kProtocolVersion = %d;" % (200 + len(messages)),
        "",
    ]
    for name, mid, fields in messages:
        out.append(f"inline constexpr std::uint16_t kId{name} = {mid};")
    out.append("")
    for name, mid, fields in messages:
        out.append(f"struct {name} {{")
        out.append(f"  static constexpr std::uint16_t kId = kId{name};")
        for ftype, fname in fields:
            dflt = DEFAULTS.get(ftype, "0")
            if ftype == "string":
                out.append(f"  std::string {fname};")
            else:
                out.append(f"  {CPP_TYPE[ftype]} {fname} = {dflt};")
        out.append("")
        out.append("  void serialize(Writer& w) const;")
        out.append("  bool deserialize(Reader r);")
        out.append("};")
        out.append("")
    out.append("const char* msgName(std::uint16_t id);")
    out.append("")
    out.append("template <typename Msg>")
    out.append("std::vector<std::uint8_t> pack(const Msg& m) {")
    out.append("  std::vector<std::uint8_t> b;")
    out.append("  b.reserve(64);")
    out.append("  Writer w(b);")
    out.append("  w.u16(Msg::kId);")
    out.append("  const size_t lenSlot = b.size();")
    out.append("  w.u16(0);")
    out.append("  m.serialize(w);")
    out.append("  const std::uint16_t len =")
    out.append("      static_cast<std::uint16_t>(b.size() - lenSlot - 2);")
    out.append("  b[lenSlot] = static_cast<std::uint8_t>(len & 0xFF);")
    out.append("  b[lenSlot + 1] = static_cast<std::uint8_t>(len >> 8);")
    out.append("  return b;")
    out.append("}")
    out.append("")
    out.append("struct PacketView {")
    out.append("  std::uint16_t id = 0;")
    out.append("  Reader body{nullptr, 0};")
    out.append("  bool ok = false;")
    out.append("};")
    out.append("")
    out.append("inline PacketView view(const std::uint8_t* data, size_t len) {")
    out.append("  PacketView pv;")
    out.append("  if (data == nullptr || len < 4) return pv;")
    out.append("  Reader h(data, len);")
    out.append("  std::uint16_t id = 0, plen = 0;")
    out.append("  if (!h.u16(id) || !h.u16(plen)) return pv;")
    out.append("  if (len - 4 != plen) return pv;")
    out.append("  pv.id = id;")
    out.append("  pv.body = Reader(data + 4, plen);")
    out.append("  pv.ok = true;")
    out.append("  return pv;")
    out.append("}")
    out.append("")
    out.append("}  // namespace bh::proto")
    out.append("")
    return "\n".join(out)


def emit_cpp(messages):
    out = [
        "// GENERATED by tools/protogen/protogen.py - do not edit.",
        '#include "protocol/messages_gen.h"',
        "",
        "namespace bh::proto {",
        "",
    ]
    for name, mid, fields in sorted(messages, key=lambda m: m[1]):
        out.append(f"void {name}::serialize(Writer& w) const {{")
        for ftype, fname in fields:
            m = WRITER.get(ftype, ftype)
            out.append(f"  w.{m}({fname});")
        out.append("}")
        out.append("")
        out.append(f"bool {name}::deserialize(Reader r) {{")
        for ftype, fname in fields:
            m = READER.get(ftype, ftype)
            out.append(f"  if (!r.{m}({fname})) return false;")
        out.append("  return true;" if fields else "  (void)r;\n  return true;")
        out.append("}")
        out.append("")
    # a message with no fields: '(void)r; return true;' emitted twice if fields empty -> handle
    out.append("const char* msgName(std::uint16_t id) {")
    out.append("  switch (id) {")
    for name, mid, fields in sorted(messages, key=lambda m: m[1]):
        out.append(f"    case kId{name}: return \"{name}\";")
    out.append("    default: return \"unknown\";")
    out.append("  }")
    out.append("}")
    out.append("")
    out.append("}  // namespace bh::proto")
    out.append("")
    return "\n".join(out)


def main():
    if len(sys.argv) != 3:
        raise SystemExit("usage: protogen.py <messages.md> <out_dir>")
    src = Path(sys.argv[1])
    outdir = Path(sys.argv[2])
    outdir.mkdir(parents=True, exist_ok=True)
    messages = parse(src.read_text(), str(src))
    if not messages:
        raise SystemExit(f"{src}: no proto blocks found")
    (outdir / "messages_gen.h").write_text(emit_h(messages))
    (outdir / "messages_gen.cpp").write_text(emit_cpp(messages))
    print(f"protogen: {len(messages)} messages -> {outdir}")


if __name__ == "__main__":
    main()
